-- Recetas Fudo — generado automáticamente
CREATE TABLE IF NOT EXISTS recetas_fudo (
  id          serial PRIMARY KEY,
  producto_fudo text NOT NULL,
  ingrediente   text NOT NULL,
  cantidad      numeric NOT NULL,
  unidad        text NOT NULL DEFAULT 'kg',
  tabla_origen  text NOT NULL DEFAULT 'stock_produccion'
);

-- Limpiar y recargar
TRUNCATE recetas_fudo RESTART IDENTITY;

INSERT INTO recetas_fudo (producto_fudo, ingrediente, cantidad, unidad, tabla_origen) VALUES
  ('1 lomo americano', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo americano', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo americano', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('1 lomo americano', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('1 lomo americano', 'BARBACOA', 0.025, 'kg', 'stock'),
  ('1 lomo americano', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo americano delux', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo americano delux', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo americano delux', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('1 lomo americano delux', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('1 lomo americano delux', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo americano delux', 'BARBACOA', 0.025, 'kg', 'stock'),
  ('1 lomo americano delux', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo clasico', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo clasico', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo clasico', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('1 lomo clasico', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo clasico', 'HUEVO', 1, 'u', 'stock'),
  ('1 lomo clasico', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo clasico', 'QUESO TYBO', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo clasico', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo clasico', 'SALSA DE AJO CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo clasico', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo criollo', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo criollo', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo criollo', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'QUESO TYBO', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'CRIOLLA', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'SALSA DE AJO CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo criollo', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo napolitano', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo napolitano', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo napolitano', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo napolitano', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo napolitano', 'TOMATES SECOS PREPARADOS', 0.06, 'kg', 'stock_produccion'),
  ('1 lomo napolitano', 'OREGANO', 0.002, 'kg', 'stock'),
  ('1 lomo napolitano', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo napolitano', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo napolitano.', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo napolitano.', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo napolitano.', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo napolitano.', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo napolitano.', 'TOMATES SECOS PREPARADOS', 0.06, 'kg', 'stock_produccion'),
  ('1 lomo napolitano.', 'OREGANO', 0.002, 'kg', 'stock'),
  ('1 lomo napolitano.', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo napolitano.', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo oklahoma', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo oklahoma', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo oklahoma', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('1 lomo oklahoma', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo oklahoma', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo oklahoma', 'SALSA DE AJO CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo oklahoma', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo provoleta', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo provoleta', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo provoleta', 'PROVOLETA', 0.08, 'kg', 'stock_produccion'),
  ('1 lomo provoleta', 'OREGANO', 0.002, 'kg', 'stock'),
  ('1 lomo provoleta', 'HUEVO', 1, 'u', 'stock'),
  ('1 lomo provoleta', 'Morrón preparado', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo provoleta', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo provoleta', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo provoleta.', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo provoleta.', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo provoleta.', 'PROVOLETA', 0.08, 'kg', 'stock_produccion'),
  ('1 lomo provoleta.', 'OREGANO', 0.002, 'kg', 'stock'),
  ('1 lomo provoleta.', 'HUEVO', 1, 'u', 'stock'),
  ('1 lomo provoleta.', 'Morrón preparado', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo provoleta.', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo provoleta.', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('1 lomo vegetariano', 'Bifes Lomito_Lomo', 1.0, 'u', 'stock_produccion'),
  ('1 lomo vegetariano', 'Pan de Lomito', 1.0, 'u', 'stock_produccion'),
  ('1 lomo vegetariano', 'PROVOLETA', 0.08, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'HUEVO', 1, 'u', 'stock'),
  ('1 lomo vegetariano', 'Morrón preparado', 0.03, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'SALSA DE AJO CLUB', 0.025, 'kg', 'stock_produccion'),
  ('1 lomo vegetariano', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('animal style doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('animal style doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('animal style doble', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('animal style doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('animal style simple', 'Medallones Burger', 1.0, 'u', 'stock_produccion'),
  ('animal style simple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('animal style simple', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('animal style simple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('animal style triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('animal style triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('animal style triple', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('animal style triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon crispy doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('bacon crispy doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon crispy doble', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon crispy doble', 'CHEDDAR EN FETA', 0.1, 'kg', 'stock_produccion'),
  ('bacon crispy doble', 'SALSA SPREAD', 0.025, 'kg', 'stock_produccion'),
  ('bacon crispy doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon crispy simple f', 'Medallones Burger', 1.0, 'u', 'stock_produccion'),
  ('bacon crispy simple f', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon crispy simple f', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon crispy simple f', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon crispy simple f', 'SALSA SPREAD', 0.025, 'kg', 'stock_produccion'),
  ('bacon crispy simple f', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon crispy triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('bacon crispy triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon crispy triple', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon crispy triple', 'CHEDDAR EN FETA', 0.15, 'kg', 'stock_produccion'),
  ('bacon crispy triple', 'SALSA SPREAD', 0.025, 'kg', 'stock_produccion'),
  ('bacon crispy triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon cuádruple', 'Medallones Burger', 4.0, 'u', 'stock_produccion'),
  ('bacon cuádruple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon cuádruple', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon cuádruple', 'CHEDDAR EN FETA', 0.2, 'kg', 'stock_produccion'),
  ('bacon cuádruple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('bacon doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon doble', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon doble', 'CHEDDAR EN FETA', 0.1, 'kg', 'stock_produccion'),
  ('bacon doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon jam doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('bacon jam doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon jam doble', 'CHEDDAR EN FETA', 0.1, 'kg', 'stock_produccion'),
  ('bacon jam doble', 'SALSA JAM', 0.025, 'kg', 'stock_produccion'),
  ('bacon jam doble', 'SALSA CREMA', 0.025, 'kg', 'stock_produccion'),
  ('bacon jam doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon jam triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('bacon jam triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon jam triple', 'CHEDDAR EN FETA', 0.15, 'kg', 'stock_produccion'),
  ('bacon jam triple', 'SALSA JAM', 0.025, 'kg', 'stock_produccion'),
  ('bacon jam triple', 'SALSA CREMA', 0.025, 'kg', 'stock_produccion'),
  ('bacon jam triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon simple', 'Medallones Burger', 1.0, 'u', 'stock_produccion'),
  ('bacon simple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon simple', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon simple', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon simple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('bacon triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('bacon triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('bacon triple', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('bacon triple', 'CHEDDAR EN FETA', 0.15, 'kg', 'stock_produccion'),
  ('bacon triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('cheese cuádruple', 'Medallones Burger', 4.0, 'u', 'stock_produccion'),
  ('cheese cuádruple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('cheese cuádruple', 'CHEDDAR EN FETA', 0.2, 'kg', 'stock_produccion'),
  ('cheese cuádruple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('cheese doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('cheese doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('cheese doble', 'CHEDDAR EN FETA', 0.1, 'kg', 'stock_produccion'),
  ('cheese doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('cheese simple', 'Medallones Burger', 1.0, 'u', 'stock_produccion'),
  ('cheese simple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('cheese simple', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('cheese simple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('cheese triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('cheese triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('cheese triple', 'CHEDDAR EN FETA', 0.15, 'kg', 'stock_produccion'),
  ('cheese triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('la club doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('la club doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('la club doble', 'CHEDDAR EN FETA', 0.1, 'kg', 'stock_produccion'),
  ('la club doble', 'SALSA CREMA', 0.025, 'kg', 'stock_produccion'),
  ('la club doble', 'SALSA SPREAD', 0.025, 'kg', 'stock_produccion'),
  ('la club doble', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('la club doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('la club simple', 'Medallones Burger', 1.0, 'u', 'stock_produccion'),
  ('la club simple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('la club simple', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('la club simple', 'SALSA CREMA', 0.025, 'kg', 'stock_produccion'),
  ('la club simple', 'SALSA SPREAD', 0.025, 'kg', 'stock_produccion'),
  ('la club simple', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('la club simple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('la club triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('la club triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('la club triple', 'CHEDDAR EN FETA', 0.15, 'kg', 'stock_produccion'),
  ('la club triple', 'SALSA CREMA', 0.025, 'kg', 'stock_produccion'),
  ('la club triple', 'SALSA SPREAD', 0.025, 'kg', 'stock_produccion'),
  ('la club triple', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('la club triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('peaky doble', 'Medallones Burger', 2.0, 'u', 'stock_produccion'),
  ('peaky doble', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('peaky doble', 'CHEDDAR EN FETA', 0.1, 'kg', 'stock_produccion'),
  ('peaky doble', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('peaky doble', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('peaky triple', 'Medallones Burger', 3.0, 'u', 'stock_produccion'),
  ('peaky triple', 'PAN KALIS', 1.0, 'u', 'stock'),
  ('peaky triple', 'CHEDDAR EN FETA', 0.15, 'kg', 'stock_produccion'),
  ('peaky triple', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('peaky triple', 'CAJAS BURGUER', 1.0, 'u', 'stock_produccion'),
  ('clasico tucumano f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('clasico tucumano f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('clasico tucumano f', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('clasico tucumano f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('clasico tucumano f', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('clasico tucumano f', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('clásico tucumano', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('clásico tucumano', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('clásico tucumano', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('clásico tucumano', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('clásico tucumano', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('clásico tucumano', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('especial cebolla tucumano f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('especial cebolla tucumano f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('especial cebolla tucumano f', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano f', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano f', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano f', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('especial cebolla tucumano', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('especial cebolla tucumano', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('especial cebolla tucumano', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('especial cebolla tucumano', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('milanesa bacon al plato f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa bacon al plato f', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa bacon al plato f', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa bacon al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa box.', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa box.', 'CAJAS MILA BOX', 1.0, 'u', 'stock_produccion'),
  ('milanesa cebolla caramelizada al plato f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa cebolla caramelizada al plato f', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('milanesa cebolla caramelizada al plato f', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('milanesa cebolla caramelizada al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa criollo f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa criollo f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa criollo f', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('milanesa criollo f', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('milanesa criollo f', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('milanesa criollo f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('milanesa criollo f', 'CRIOLLA', 0.04, 'kg', 'stock_produccion'),
  ('milanesa criollo f', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('milanesa criollo f', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('milanesa delux f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa delux f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa delux f', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa delux f', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('milanesa delux f', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa delux f', 'BARBACOA', 0.025, 'kg', 'stock'),
  ('milanesa delux f', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitana al plato f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitana al plato f', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('milanesa napolitana al plato f', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('milanesa napolitana al plato f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('milanesa napolitana al plato f', 'OREGANO', 0.002, 'kg', 'stock'),
  ('milanesa napolitana al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitano f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitano f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitano f', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('milanesa napolitano f', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('milanesa napolitano f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('milanesa napolitano f', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('milanesa napolitano f', 'OREGANO', 0.002, 'kg', 'stock'),
  ('milanesa napolitano f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa porteña al plato f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa porteña al plato f', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('milanesa porteña al plato f', 'SALSA PESTO', 0.025, 'kg', 'stock_produccion'),
  ('milanesa porteña al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa al plato f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitana al plato', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitana al plato', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('milanesa napolitana al plato', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('milanesa napolitana al plato', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('milanesa napolitana al plato', 'OREGANO', 0.002, 'kg', 'stock'),
  ('milanesa napolitana al plato', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa al plato peya', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa al plato peya', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa bacon al plato', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa bacon al plato', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa bacon al plato', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa bacon al plato', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('milanesa box', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa box', 'CAJAS MILA BOX', 1.0, 'u', 'stock_produccion'),
  ('milanesa cebolla caramelizada', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa cebolla caramelizada', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa cebolla caramelizada', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('milanesa cebolla caramelizada', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa cebolla caramelizada', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('milanesa cebolla caramelizada', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('milanesa criollo', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa criollo', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa criollo', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('milanesa criollo', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('milanesa criollo', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('milanesa criollo', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('milanesa criollo', 'CRIOLLA', 0.04, 'kg', 'stock_produccion'),
  ('milanesa criollo', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('milanesa criollo', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('milanesa delux', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa delux', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa delux', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa delux', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('milanesa delux', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('milanesa delux', 'BARBACOA', 0.025, 'kg', 'stock'),
  ('milanesa delux', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitano', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitano', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('milanesa napolitano', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('milanesa napolitano', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('milanesa napolitano', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('milanesa napolitano', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('milanesa napolitano', 'OREGANO', 0.002, 'kg', 'stock'),
  ('milanesa napolitano', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('simple tucumano f', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('simple tucumano f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('simple tucumano f', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('simple tucumano f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('simple tucumano f', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('simple tucumano f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('simple tucumano', 'Milanesa de Carne Empanada', 1.0, 'u', 'stock_produccion'),
  ('simple tucumano', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('simple tucumano', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('simple tucumano', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('simple tucumano', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('simple tucumano', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema al plato f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema bacon al plato f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema bacon al plato f', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema bacon al plato f', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema bacon al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema box.', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema box.', 'CAJAS MILA BOX', 1.0, 'u', 'stock_produccion'),
  ('suprema cebolla caramelizada plato f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema cebolla caramelizada plato f', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('suprema cebolla caramelizada plato f', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('suprema cebolla caramelizada plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema clasico f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema clasico f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('suprema clasico f', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('suprema clasico f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('suprema clasico f', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('suprema clasico f', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('suprema delux f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema delux f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('suprema delux f', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema delux f', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('suprema delux f', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema delux f', 'BARBACOA', 0.025, 'kg', 'stock'),
  ('suprema delux f', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitana al plato f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitana al plato f', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('suprema napolitana al plato f', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('suprema napolitana al plato f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('suprema napolitana al plato f', 'OREGANO', 0.002, 'kg', 'stock'),
  ('suprema napolitana al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitano f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitano f', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitano f', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('suprema napolitano f', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('suprema napolitano f', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('suprema napolitano f', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('suprema napolitano f', 'OREGANO', 0.002, 'kg', 'stock'),
  ('suprema napolitano f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema porteña al plato f', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema porteña al plato f', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('suprema porteña al plato f', 'SALSA PESTO', 0.025, 'kg', 'stock_produccion'),
  ('suprema porteña al plato f', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema al plato', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema al plato', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema bacon al plato', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema bacon al plato', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema bacon al plato', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema bacon al plato', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema box', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema box', 'CAJAS MILA BOX', 1.0, 'u', 'stock_produccion'),
  ('suprema clasico', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema clasico', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('suprema clasico', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('suprema clasico', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('suprema clasico', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('suprema clasico', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('suprema delux', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema delux', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('suprema delux', 'PANCETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema delux', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('suprema delux', 'CHEDDAR EN FETA', 0.05, 'kg', 'stock_produccion'),
  ('suprema delux', 'BARBACOA', 0.025, 'kg', 'stock'),
  ('suprema delux', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitana al plato', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitana al plato', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('suprema napolitana al plato', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('suprema napolitana al plato', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('suprema napolitana al plato', 'OREGANO', 0.002, 'kg', 'stock'),
  ('suprema napolitana al plato', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitano', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitano', 'Pan Sanguchero', 1.0, 'u', 'stock_produccion'),
  ('suprema napolitano', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('suprema napolitano', 'Queso Muzza para Sanguchería', 0.04, 'kg', 'stock_produccion'),
  ('suprema napolitano', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('suprema napolitano', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('suprema napolitano', 'OREGANO', 0.002, 'kg', 'stock'),
  ('suprema napolitano', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('suprema cebolla caramelizada', 'Milanesa de Pollo Empanada', 1.0, 'u', 'stock_produccion'),
  ('suprema cebolla caramelizada', 'Queso Muzza para Mila al Plato', 0.06, 'kg', 'stock_produccion'),
  ('suprema cebolla caramelizada', 'CEBOLLA CARAMELIZADA', 0.04, 'kg', 'stock_produccion'),
  ('suprema cebolla caramelizada', 'CAJA MILA AL PLATO', 1.0, 'u', 'stock_produccion'),
  ('promo suprema clasica x2', 'Milanesa de Pollo Empanada', 2.0, 'u', 'stock_produccion'),
  ('promo suprema clasica x2', 'Pan Sanguchero', 2.0, 'u', 'stock_produccion'),
  ('promo suprema clasica x2', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('promo suprema clasica x2', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('promo suprema clasica x2', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('promo suprema clasica x2', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('promo clasico x2', 'Bifes Lomito_Lomo', 2.0, 'u', 'stock_produccion'),
  ('promo clasico x2', 'Pan de Lomito', 2.0, 'u', 'stock_produccion'),
  ('promo clasico x2', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('promo clasico x2', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('promo clasico x2', 'HUEVO', 1, 'u', 'stock'),
  ('promo clasico x2', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('promo clasico x2', 'QUESO TYBO', 0.03, 'kg', 'stock_produccion'),
  ('promo clasico x2', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('promo clasico x2', 'SALSA DE AJO CLUB', 0.025, 'kg', 'stock_produccion'),
  ('promo clasico x2', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion'),
  ('promo mila clasica  x2.', 'Milanesa de Carne Empanada', 2.0, 'u', 'stock_produccion'),
  ('promo mila clasica  x2.', 'Pan Sanguchero', 2.0, 'u', 'stock_produccion'),
  ('promo mila clasica  x2.', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('promo mila clasica  x2.', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('promo mila clasica  x2.', 'MAYO MILA', 0.025, 'kg', 'stock_produccion'),
  ('promo mila clasica  x2.', 'CAJAS MILANESA INDIVIDUAL', 1.0, 'u', 'stock_produccion'),
  ('promo sanguche clasico x2', 'Bifes Lomito_Cuadril', 2.0, 'u', 'stock_produccion'),
  ('promo sanguche clasico x2', 'Pan de Lomito', 2.0, 'u', 'stock_produccion'),
  ('promo sanguche clasico x2', 'TOMATE', 0.06, 'kg', 'stock_produccion'),
  ('promo sanguche clasico x2', 'Lechuga preparada', 0.03, 'kg', 'stock_produccion'),
  ('promo sanguche clasico x2', 'HUEVO', 1, 'u', 'stock'),
  ('promo sanguche clasico x2', 'JAMÓN', 0.04, 'kg', 'stock_produccion'),
  ('promo sanguche clasico x2', 'QUESO TYBO', 0.03, 'kg', 'stock_produccion'),
  ('promo sanguche clasico x2', 'SALSA CLUB', 0.025, 'kg', 'stock_produccion'),
  ('promo sanguche clasico x2', 'SALSA DE AJO CLUB', 0.025, 'kg', 'stock_produccion'),
  ('promo sanguche clasico x2', 'CAJAS LOMITOS', 1.0, 'u', 'stock_produccion');

-- Total: 434 filas, 75 productos distintos

-- RLS
ALTER TABLE recetas_fudo ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "lectura publica recetas_fudo" ON recetas_fudo;
CREATE POLICY "lectura publica recetas_fudo" ON recetas_fudo
  FOR SELECT TO anon, authenticated USING (true);
